//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace Cartomatic.OgcSchemas.Ows
{
    namespace Ows_1103
    {

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Identifier", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class CodeType
        {

            private string codeSpaceField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
            public string codeSpace
            {
                get { return this.codeSpaceField; }
                set { this.codeSpaceField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get { return this.valueField; }
                set { this.valueField = value; }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (ReferenceType))]
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (ServiceReferenceType))]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class AbstractReferenceBaseType
        {

            private string typeField;

            private string hrefField;

            private string roleField;

            private string arcroleField;

            private string titleField;

            private showType showField;

            private bool showFieldSpecified;

            private actuateType actuateField;

            private bool actuateFieldSpecified;

            public AbstractReferenceBaseType()
            {
                this.typeField = "simple";
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public string type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string href
            {
                get { return this.hrefField; }
                set { this.hrefField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string arcrole
            {
                get { return this.arcroleField; }
                set { this.arcroleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public string title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public showType show
            {
                get { return this.showField; }
                set { this.showField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool showSpecified
            {
                get { return this.showFieldSpecified; }
                set { this.showFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public actuateType actuate
            {
                get { return this.actuateField; }
                set { this.actuateField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool actuateSpecified
            {
                get { return this.actuateFieldSpecified; }
                set { this.actuateFieldSpecified = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public enum showType
        {

            /// <remarks/>
            @new,

            /// <remarks/>
            replace,

            /// <remarks/>
            embed,

            /// <remarks/>
            other,

            /// <remarks/>
            none,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public enum actuateType
        {

            /// <remarks/>
            onLoad,

            /// <remarks/>
            onRequest,

            /// <remarks/>
            other,

            /// <remarks/>
            none,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class ContentsBaseType
        {

            private DatasetDescriptionSummaryBaseType[] datasetDescriptionSummaryField;

            private MetadataType[] otherSourceField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("DatasetDescriptionSummary")]
            public DatasetDescriptionSummaryBaseType[] DatasetDescriptionSummary
            {
                get { return this.datasetDescriptionSummaryField; }
                set { this.datasetDescriptionSummaryField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("OtherSource")]
            public MetadataType[] OtherSource
            {
                get { return this.otherSourceField; }
                set { this.otherSourceField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("DatasetDescriptionSummary",
            Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class DatasetDescriptionSummaryBaseType : DescriptionType
        {

            private WGS84BoundingBoxType[] wGS84BoundingBoxField;

            private CodeType identifierField;

            private BoundingBoxType[] itemsField;

            private MetadataType[] metadataField;

            private DatasetDescriptionSummaryBaseType[] datasetDescriptionSummaryField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("WGS84BoundingBox")]
            public WGS84BoundingBoxType[] WGS84BoundingBox
            {
                get { return this.wGS84BoundingBoxField; }
                set { this.wGS84BoundingBoxField = value; }
            }

            /// <remarks/>
            public CodeType Identifier
            {
                get { return this.identifierField; }
                set { this.identifierField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("BoundingBox", typeof (BoundingBoxType))]
            [System.Xml.Serialization.XmlElementAttribute("WGS84BoundingBox", typeof (WGS84BoundingBoxType))]
            public BoundingBoxType[] Items
            {
                get { return this.itemsField; }
                set { this.itemsField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Metadata")]
            public MetadataType[] Metadata
            {
                get { return this.metadataField; }
                set { this.metadataField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("DatasetDescriptionSummary")]
            public DatasetDescriptionSummaryBaseType[] DatasetDescriptionSummary
            {
                get { return this.datasetDescriptionSummaryField; }
                set { this.datasetDescriptionSummaryField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("WGS84BoundingBox", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class WGS84BoundingBoxType : BoundingBoxType
        {
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (WGS84BoundingBoxType))]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("BoundingBox", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class BoundingBoxType
        {

            private string lowerCornerField;

            private string upperCornerField;

            private string crsField;

            private string dimensionsField;

            /// <remarks/>
            public string LowerCorner
            {
                get { return this.lowerCornerField; }
                set { this.lowerCornerField = value; }
            }

            /// <remarks/>
            public string UpperCorner
            {
                get { return this.upperCornerField; }
                set { this.upperCornerField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
            public string crs
            {
                get { return this.crsField; }
                set { this.crsField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "positiveInteger")]
            public string dimensions
            {
                get { return this.dimensionsField; }
                set { this.dimensionsField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("OtherSource", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class MetadataType
        {

            private object abstractMetaDataField;

            private typeType typeField;

            private bool typeFieldSpecified;

            private string hrefField;

            private string roleField;

            private string arcroleField;

            private string titleField;

            private showType showField;

            private bool showFieldSpecified;

            private actuateType actuateField;

            private bool actuateFieldSpecified;

            private string aboutField;

            public MetadataType()
            {
                this.typeField = typeType.simple;
            }

            /// <remarks/>
            public object AbstractMetaData
            {
                get { return this.abstractMetaDataField; }
                set { this.abstractMetaDataField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public typeType type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool typeSpecified
            {
                get { return this.typeFieldSpecified; }
                set { this.typeFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string href
            {
                get { return this.hrefField; }
                set { this.hrefField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string arcrole
            {
                get { return this.arcroleField; }
                set { this.arcroleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public string title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public showType show
            {
                get { return this.showField; }
                set { this.showField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool showSpecified
            {
                get { return this.showFieldSpecified; }
                set { this.showFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public actuateType actuate
            {
                get { return this.actuateField; }
                set { this.actuateField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool actuateSpecified
            {
                get { return this.actuateFieldSpecified; }
                set { this.actuateFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
            public string about
            {
                get { return this.aboutField; }
                set { this.aboutField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public enum typeType
        {

            /// <remarks/>
            simple,

            /// <remarks/>
            extended,

            /// <remarks/>
            title,

            /// <remarks/>
            resource,

            /// <remarks/>
            locator,

            /// <remarks/>
            arc,
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (DatasetDescriptionSummaryBaseType))]
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (BasicIdentificationType))]
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (ManifestType))]
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (ReferenceGroupType))]
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (IdentificationType))]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class DescriptionType
        {

            private LanguageStringType[] titleField;

            private LanguageStringType[] abstractField;

            private KeywordsType[] keywordsField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Title")]
            public LanguageStringType[] Title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Abstract")]
            public LanguageStringType[] Abstract
            {
                get { return this.abstractField; }
                set { this.abstractField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Keywords")]
            public KeywordsType[] Keywords
            {
                get { return this.keywordsField; }
                set { this.keywordsField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Title", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class LanguageStringType
        {

            private string langField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/XML/1998/namespace")]
            public string lang
            {
                get { return this.langField; }
                set { this.langField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get { return this.valueField; }
                set { this.valueField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Keywords", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class KeywordsType
        {

            private LanguageStringType[] keywordField;

            private CodeType typeField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Keyword")]
            public LanguageStringType[] Keyword
            {
                get { return this.keywordField; }
                set { this.keywordField = value; }
            }

            /// <remarks/>
            public CodeType Type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (ManifestType))]
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (ReferenceGroupType))]
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (IdentificationType))]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class BasicIdentificationType : DescriptionType
        {

            private CodeType identifierField;

            private MetadataType[] metadataField;

            /// <remarks/>
            public CodeType Identifier
            {
                get { return this.identifierField; }
                set { this.identifierField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Metadata")]
            public MetadataType[] Metadata
            {
                get { return this.metadataField; }
                set { this.metadataField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class IdentificationType : BasicIdentificationType
        {

            private BoundingBoxType[] itemsField;

            private string[] outputFormatField;

            private string[] availableCRSField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("BoundingBox", typeof (BoundingBoxType))]
            [System.Xml.Serialization.XmlElementAttribute("WGS84BoundingBox", typeof (WGS84BoundingBoxType))]
            public BoundingBoxType[] Items
            {
                get { return this.itemsField; }
                set { this.itemsField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("OutputFormat")]
            public string[] OutputFormat
            {
                get { return this.outputFormatField; }
                set { this.outputFormatField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("AvailableCRS", DataType = "anyURI")]
            public string[] AvailableCRS
            {
                get { return this.availableCRSField; }
                set { this.availableCRSField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class CapabilitiesBaseType
        {

            private ServiceIdentification serviceIdentificationField;

            private ServiceProvider serviceProviderField;

            private OperationsMetadata operationsMetadataField;

            private string versionField;

            private string updateSequenceField;

            /// <remarks/>
            public ServiceIdentification ServiceIdentification
            {
                get { return this.serviceIdentificationField; }
                set { this.serviceIdentificationField = value; }
            }

            /// <remarks/>
            public ServiceProvider ServiceProvider
            {
                get { return this.serviceProviderField; }
                set { this.serviceProviderField = value; }
            }

            /// <remarks/>
            public OperationsMetadata OperationsMetadata
            {
                get { return this.operationsMetadataField; }
                set { this.operationsMetadataField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string version
            {
                get { return this.versionField; }
                set { this.versionField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string updateSequence
            {
                get { return this.updateSequenceField; }
                set { this.updateSequenceField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class ServiceIdentification : DescriptionType
        {

            private CodeType serviceTypeField;

            private string[] serviceTypeVersionField;

            private string[] profileField;

            private string feesField;

            private string[] accessConstraintsField;

            /// <remarks/>
            public CodeType ServiceType
            {
                get { return this.serviceTypeField; }
                set { this.serviceTypeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ServiceTypeVersion")]
            public string[] ServiceTypeVersion
            {
                get { return this.serviceTypeVersionField; }
                set { this.serviceTypeVersionField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Profile", DataType = "anyURI")]
            public string[] Profile
            {
                get { return this.profileField; }
                set { this.profileField = value; }
            }

            /// <remarks/>
            public string Fees
            {
                get { return this.feesField; }
                set { this.feesField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("AccessConstraints")]
            public string[] AccessConstraints
            {
                get { return this.accessConstraintsField; }
                set { this.accessConstraintsField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class ServiceProvider
        {

            private string providerNameField;

            private OnlineResourceType providerSiteField;

            private ResponsiblePartySubsetType serviceContactField;

            /// <remarks/>
            public string ProviderName
            {
                get { return this.providerNameField; }
                set { this.providerNameField = value; }
            }

            /// <remarks/>
            public OnlineResourceType ProviderSite
            {
                get { return this.providerSiteField; }
                set { this.providerSiteField = value; }
            }

            /// <remarks/>
            public ResponsiblePartySubsetType ServiceContact
            {
                get { return this.serviceContactField; }
                set { this.serviceContactField = value; }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (RequestMethodType))]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class OnlineResourceType
        {

            private typeType typeField;

            private bool typeFieldSpecified;

            private string hrefField;

            private string roleField;

            private string arcroleField;

            private string titleField;

            private showType showField;

            private bool showFieldSpecified;

            private actuateType actuateField;

            private bool actuateFieldSpecified;

            public OnlineResourceType()
            {
                this.typeField = typeType.simple;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public typeType type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool typeSpecified
            {
                get { return this.typeFieldSpecified; }
                set { this.typeFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string href
            {
                get { return this.hrefField; }
                set { this.hrefField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
            public string arcrole
            {
                get { return this.arcroleField; }
                set { this.arcroleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public string title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public showType show
            {
                get { return this.showField; }
                set { this.showField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool showSpecified
            {
                get { return this.showFieldSpecified; }
                set { this.showFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/1999/xlink")]
            public actuateType actuate
            {
                get { return this.actuateField; }
                set { this.actuateField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool actuateSpecified
            {
                get { return this.actuateFieldSpecified; }
                set { this.actuateFieldSpecified = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class RequestMethodType : OnlineResourceType
        {

            private DomainType[] constraintField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Constraint")]
            public DomainType[] Constraint
            {
                get { return this.constraintField; }
                set { this.constraintField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class DomainType : UnNamedDomainType
        {

            private string nameField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name
            {
                get { return this.nameField; }
                set { this.nameField = value; }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (DomainType))]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class UnNamedDomainType
        {

            private object[] allowedValuesField;

            private AnyValue anyValueField;

            private NoValues noValuesField;

            private ValuesReference valuesReferenceField;

            private ValueType defaultValueField;

            private DomainMetadataType meaningField;

            private DomainMetadataType dataTypeField;

            private DomainMetadataType uOMField;

            private DomainMetadataType referenceSystemField;

            private MetadataType[] metadataField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Range", typeof (RangeType), IsNullable = false)]
            [System.Xml.Serialization.XmlArrayItemAttribute("Value", typeof (ValueType), IsNullable = false)]
            public object[] AllowedValues
            {
                get { return this.allowedValuesField; }
                set { this.allowedValuesField = value; }
            }

            /// <remarks/>
            public AnyValue AnyValue
            {
                get { return this.anyValueField; }
                set { this.anyValueField = value; }
            }

            /// <remarks/>
            public NoValues NoValues
            {
                get { return this.noValuesField; }
                set { this.noValuesField = value; }
            }

            /// <remarks/>
            public ValuesReference ValuesReference
            {
                get { return this.valuesReferenceField; }
                set { this.valuesReferenceField = value; }
            }

            /// <remarks/>
            public ValueType DefaultValue
            {
                get { return this.defaultValueField; }
                set { this.defaultValueField = value; }
            }

            /// <remarks/>
            public DomainMetadataType Meaning
            {
                get { return this.meaningField; }
                set { this.meaningField = value; }
            }

            /// <remarks/>
            public DomainMetadataType DataType
            {
                get { return this.dataTypeField; }
                set { this.dataTypeField = value; }
            }

            /// <remarks/>
            public DomainMetadataType UOM
            {
                get { return this.uOMField; }
                set { this.uOMField = value; }
            }

            /// <remarks/>
            public DomainMetadataType ReferenceSystem
            {
                get { return this.referenceSystemField; }
                set { this.referenceSystemField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Metadata")]
            public MetadataType[] Metadata
            {
                get { return this.metadataField; }
                set { this.metadataField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Range", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class RangeType
        {

            private ValueType minimumValueField;

            private ValueType maximumValueField;

            private ValueType spacingField;

            private RangeTypeRangeClosure rangeClosureField;

            private bool rangeClosureFieldSpecified;

            public RangeType()
            {
                this.rangeClosureField = RangeTypeRangeClosure.closed;
            }

            /// <remarks/>
            public ValueType MinimumValue
            {
                get { return this.minimumValueField; }
                set { this.minimumValueField = value; }
            }

            /// <remarks/>
            public ValueType MaximumValue
            {
                get { return this.maximumValueField; }
                set { this.maximumValueField = value; }
            }

            /// <remarks/>
            public ValueType Spacing
            {
                get { return this.spacingField; }
                set { this.spacingField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            [System.ComponentModel.DefaultValueAttribute(RangeTypeRangeClosure.closed)]
            public RangeTypeRangeClosure rangeClosure
            {
                get { return this.rangeClosureField; }
                set { this.rangeClosureField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool rangeClosureSpecified
            {
                get { return this.rangeClosureFieldSpecified; }
                set { this.rangeClosureFieldSpecified = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Value", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class ValueType
        {

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get { return this.valueField; }
                set { this.valueField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        public enum RangeTypeRangeClosure
        {

            /// <remarks/>
            closed,

            /// <remarks/>
            open,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("open-closed")] openclosed,

            /// <remarks/>
            [System.Xml.Serialization.XmlEnumAttribute("closed-open")] closedopen,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class AnyValue
        {
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class NoValues
        {
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class ValuesReference
        {

            private string referenceField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string reference
            {
                get { return this.referenceField; }
                set { this.referenceField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get { return this.valueField; }
                set { this.valueField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Meaning", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class DomainMetadataType
        {

            private string referenceField;

            private string valueField;

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string reference
            {
                get { return this.referenceField; }
                set { this.referenceField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            public string Value
            {
                get { return this.valueField; }
                set { this.valueField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class ResponsiblePartySubsetType
        {

            private string individualNameField;

            private string positionNameField;

            private ContactType contactInfoField;

            private CodeType roleField;

            /// <remarks/>
            public string IndividualName
            {
                get { return this.individualNameField; }
                set { this.individualNameField = value; }
            }

            /// <remarks/>
            public string PositionName
            {
                get { return this.positionNameField; }
                set { this.positionNameField = value; }
            }

            /// <remarks/>
            public ContactType ContactInfo
            {
                get { return this.contactInfoField; }
                set { this.contactInfoField = value; }
            }

            /// <remarks/>
            public CodeType Role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("ContactInfo", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class ContactType
        {

            private TelephoneType phoneField;

            private AddressType addressField;

            private OnlineResourceType onlineResourceField;

            private string hoursOfServiceField;

            private string contactInstructionsField;

            /// <remarks/>
            public TelephoneType Phone
            {
                get { return this.phoneField; }
                set { this.phoneField = value; }
            }

            /// <remarks/>
            public AddressType Address
            {
                get { return this.addressField; }
                set { this.addressField = value; }
            }

            /// <remarks/>
            public OnlineResourceType OnlineResource
            {
                get { return this.onlineResourceField; }
                set { this.onlineResourceField = value; }
            }

            /// <remarks/>
            public string HoursOfService
            {
                get { return this.hoursOfServiceField; }
                set { this.hoursOfServiceField = value; }
            }

            /// <remarks/>
            public string ContactInstructions
            {
                get { return this.contactInstructionsField; }
                set { this.contactInstructionsField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class TelephoneType
        {

            private string[] voiceField;

            private string[] facsimileField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Voice")]
            public string[] Voice
            {
                get { return this.voiceField; }
                set { this.voiceField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Facsimile")]
            public string[] Facsimile
            {
                get { return this.facsimileField; }
                set { this.facsimileField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        public partial class AddressType
        {

            private string[] deliveryPointField;

            private string cityField;

            private string administrativeAreaField;

            private string postalCodeField;

            private string countryField;

            private string[] electronicMailAddressField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("DeliveryPoint")]
            public string[] DeliveryPoint
            {
                get { return this.deliveryPointField; }
                set { this.deliveryPointField = value; }
            }

            /// <remarks/>
            public string City
            {
                get { return this.cityField; }
                set { this.cityField = value; }
            }

            /// <remarks/>
            public string AdministrativeArea
            {
                get { return this.administrativeAreaField; }
                set { this.administrativeAreaField = value; }
            }

            /// <remarks/>
            public string PostalCode
            {
                get { return this.postalCodeField; }
                set { this.postalCodeField = value; }
            }

            /// <remarks/>
            public string Country
            {
                get { return this.countryField; }
                set { this.countryField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ElectronicMailAddress")]
            public string[] ElectronicMailAddress
            {
                get { return this.electronicMailAddressField; }
                set { this.electronicMailAddressField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class OperationsMetadata
        {

            private Operation[] operationField;

            private DomainType[] parameterField;

            private DomainType[] constraintField;

            private object extendedCapabilitiesField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Operation")]
            public Operation[] Operation
            {
                get { return this.operationField; }
                set { this.operationField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Parameter")]
            public DomainType[] Parameter
            {
                get { return this.parameterField; }
                set { this.parameterField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Constraint")]
            public DomainType[] Constraint
            {
                get { return this.constraintField; }
                set { this.constraintField = value; }
            }

            /// <remarks/>
            public object ExtendedCapabilities
            {
                get { return this.extendedCapabilitiesField; }
                set { this.extendedCapabilitiesField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class Operation
        {

            private DCP[] dCPField;

            private DomainType[] parameterField;

            private DomainType[] constraintField;

            private MetadataType[] metadataField;

            private string nameField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("DCP")]
            public DCP[] DCP
            {
                get { return this.dCPField; }
                set { this.dCPField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Parameter")]
            public DomainType[] Parameter
            {
                get { return this.parameterField; }
                set { this.parameterField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Constraint")]
            public DomainType[] Constraint
            {
                get { return this.constraintField; }
                set { this.constraintField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Metadata")]
            public MetadataType[] Metadata
            {
                get { return this.metadataField; }
                set { this.metadataField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string name
            {
                get { return this.nameField; }
                set { this.nameField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class DCP
        {

            private HTTP itemField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("HTTP")]
            public HTTP Item
            {
                get { return this.itemField; }
                set { this.itemField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class HTTP
        {

            private RequestMethodType[] itemsField;

            private ItemsChoiceType[] itemsElementNameField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Get", typeof (RequestMethodType))]
            [System.Xml.Serialization.XmlElementAttribute("Post", typeof (RequestMethodType))]
            [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
            public RequestMethodType[] Items
            {
                get { return this.itemsField; }
                set { this.itemsField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public ItemsChoiceType[] ItemsElementName
            {
                get { return this.itemsElementNameField; }
                set { this.itemsElementNameField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1", IncludeInSchema = false
            )]
        public enum ItemsChoiceType
        {

            /// <remarks/>
            Get,

            /// <remarks/>
            Post,
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public partial class arcType
        {

            private titleEltType[] titleField;

            private typeType typeField;

            private string arcroleField;

            private string title1Field;

            private showType showField;

            private bool showFieldSpecified;

            private actuateType actuateField;

            private bool actuateFieldSpecified;

            private string fromField;

            private string toField;

            public arcType()
            {
                this.typeField = typeType.arc;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("title")]
            public titleEltType[] title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public typeType type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string arcrole
            {
                get { return this.arcroleField; }
                set { this.arcroleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute("title", Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public string title1
            {
                get { return this.title1Field; }
                set { this.title1Field = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public showType show
            {
                get { return this.showField; }
                set { this.showField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool showSpecified
            {
                get { return this.showFieldSpecified; }
                set { this.showFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public actuateType actuate
            {
                get { return this.actuateField; }
                set { this.actuateField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool actuateSpecified
            {
                get { return this.actuateFieldSpecified; }
                set { this.actuateFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "NCName")]
            public string from
            {
                get { return this.fromField; }
                set { this.fromField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "NCName")]
            public string to
            {
                get { return this.toField; }
                set { this.toField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public partial class titleEltType
        {

            private System.Xml.XmlNode[] anyField;

            private typeType typeField;

            private string langField;

            public titleEltType()
            {
                this.typeField = typeType.title;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            [System.Xml.Serialization.XmlAnyElementAttribute()]
            public System.Xml.XmlNode[] Any
            {
                get { return this.anyField; }
                set { this.anyField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public typeType type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/XML/1998/namespace")]
            public string lang
            {
                get { return this.langField; }
                set { this.langField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public partial class locatorType
        {

            private titleEltType[] titleField;

            private typeType typeField;

            private string hrefField;

            private string roleField;

            private string title1Field;

            private string labelField;

            public locatorType()
            {
                this.typeField = typeType.locator;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("title")]
            public titleEltType[] title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public typeType type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string href
            {
                get { return this.hrefField; }
                set { this.hrefField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute("title", Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public string title1
            {
                get { return this.title1Field; }
                set { this.title1Field = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "NCName")]
            public string label
            {
                get { return this.labelField; }
                set { this.labelField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public partial class resourceType
        {

            private System.Xml.XmlNode[] anyField;

            private typeType typeField;

            private string roleField;

            private string titleField;

            private string labelField;

            public resourceType()
            {
                this.typeField = typeType.resource;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            [System.Xml.Serialization.XmlAnyElementAttribute()]
            public System.Xml.XmlNode[] Any
            {
                get { return this.anyField; }
                set { this.anyField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public typeType type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public string title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "NCName")]
            public string label
            {
                get { return this.labelField; }
                set { this.labelField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public partial class extended
        {

            private object[] itemsField;

            private typeType typeField;

            private string roleField;

            private string titleField;

            public extended()
            {
                this.typeField = typeType.extended;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("arc", typeof (arcType))]
            [System.Xml.Serialization.XmlElementAttribute("locator", typeof (locatorType))]
            [System.Xml.Serialization.XmlElementAttribute("resource", typeof (resourceType))]
            [System.Xml.Serialization.XmlElementAttribute("title", typeof (titleEltType))]
            public object[] Items
            {
                get { return this.itemsField; }
                set { this.itemsField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public typeType type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public string title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.w3.org/1999/xlink")]
        public partial class simple
        {

            private System.Xml.XmlNode[] anyField;

            private typeType typeField;

            private bool typeFieldSpecified;

            private string hrefField;

            private string roleField;

            private string arcroleField;

            private string titleField;

            private showType showField;

            private bool showFieldSpecified;

            private actuateType actuateField;

            private bool actuateFieldSpecified;

            public simple()
            {
                this.typeField = typeType.simple;
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlTextAttribute()]
            [System.Xml.Serialization.XmlAnyElementAttribute()]
            public System.Xml.XmlNode[] Any
            {
                get { return this.anyField; }
                set { this.anyField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public typeType type
            {
                get { return this.typeField; }
                set { this.typeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool typeSpecified
            {
                get { return this.typeFieldSpecified; }
                set { this.typeFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string href
            {
                get { return this.hrefField; }
                set { this.hrefField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                DataType = "anyURI")]
            public string arcrole
            {
                get { return this.arcroleField; }
                set { this.arcroleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public string title
            {
                get { return this.titleField; }
                set { this.titleField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public showType show
            {
                get { return this.showField; }
                set { this.showField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool showSpecified
            {
                get { return this.showFieldSpecified; }
                set { this.showFieldSpecified = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
            public actuateType actuate
            {
                get { return this.actuateField; }
                set { this.actuateField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlIgnoreAttribute()]
            public bool actuateSpecified
            {
                get { return this.actuateFieldSpecified; }
                set { this.actuateFieldSpecified = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("PointOfContact", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class ResponsiblePartyType
        {

            private string individualNameField;

            private string organisationNameField;

            private string positionNameField;

            private ContactType contactInfoField;

            private CodeType roleField;

            /// <remarks/>
            public string IndividualName
            {
                get { return this.individualNameField; }
                set { this.individualNameField = value; }
            }

            /// <remarks/>
            public string OrganisationName
            {
                get { return this.organisationNameField; }
                set { this.organisationNameField = value; }
            }

            /// <remarks/>
            public string PositionName
            {
                get { return this.positionNameField; }
                set { this.positionNameField = value; }
            }

            /// <remarks/>
            public ContactType ContactInfo
            {
                get { return this.contactInfoField; }
                set { this.contactInfoField = value; }
            }

            /// <remarks/>
            public CodeType Role
            {
                get { return this.roleField; }
                set { this.roleField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("GetCapabilities", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class GetCapabilitiesType
        {

            private string[] acceptVersionsField;

            private string[] sectionsField;

            private string[] acceptFormatsField;

            private string updateSequenceField;

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Version", IsNullable = false)]
            public string[] AcceptVersions
            {
                get { return this.acceptVersionsField; }
                set { this.acceptVersionsField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("Section", IsNullable = false)]
            public string[] Sections
            {
                get { return this.sectionsField; }
                set { this.sectionsField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlArrayItemAttribute("OutputFormat", IsNullable = false)]
            public string[] AcceptFormats
            {
                get { return this.acceptFormatsField; }
                set { this.acceptFormatsField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string updateSequence
            {
                get { return this.updateSequenceField; }
                set { this.updateSequenceField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("GetResourceByID", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class GetResourceByIdType
        {

            private string[] resourceIDField;

            private string outputFormatField;

            private string serviceField;

            private string versionField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ResourceID", DataType = "anyURI")]
            public string[] ResourceID
            {
                get { return this.resourceIDField; }
                set { this.resourceIDField = value; }
            }

            /// <remarks/>
            public string OutputFormat
            {
                get { return this.outputFormatField; }
                set { this.outputFormatField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string service
            {
                get { return this.serviceField; }
                set { this.serviceField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string version
            {
                get { return this.versionField; }
                set { this.versionField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class ExceptionReport
        {

            private ExceptionType[] exceptionField;

            private string versionField;

            private string langField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Exception")]
            public ExceptionType[] Exception
            {
                get { return this.exceptionField; }
                set { this.exceptionField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string version
            {
                get { return this.versionField; }
                set { this.versionField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified,
                Namespace = "http://www.w3.org/XML/1998/namespace")]
            public string lang
            {
                get { return this.langField; }
                set { this.langField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Exception", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class ExceptionType
        {

            private string[] exceptionTextField;

            private string exceptionCodeField;

            private string locatorField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ExceptionText")]
            public string[] ExceptionText
            {
                get { return this.exceptionTextField; }
                set { this.exceptionTextField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string exceptionCode
            {
                get { return this.exceptionCodeField; }
                set { this.exceptionCodeField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string locator
            {
                get { return this.locatorField; }
                set { this.locatorField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.opengis.net/ows/1.1", IsNullable = false)]
        public partial class AllowedValues
        {

            private object[] itemsField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Range", typeof (RangeType))]
            [System.Xml.Serialization.XmlElementAttribute("Value", typeof (ValueType))]
            public object[] Items
            {
                get { return this.itemsField; }
                set { this.itemsField = value; }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIncludeAttribute(typeof (ServiceReferenceType))]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Reference", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class ReferenceType : AbstractReferenceBaseType
        {

            private CodeType identifierField;

            private LanguageStringType[] abstractField;

            private string formatField;

            private MetadataType[] metadataField;

            /// <remarks/>
            public CodeType Identifier
            {
                get { return this.identifierField; }
                set { this.identifierField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Abstract")]
            public LanguageStringType[] Abstract
            {
                get { return this.abstractField; }
                set { this.abstractField = value; }
            }

            /// <remarks/>
            public string Format
            {
                get { return this.formatField; }
                set { this.formatField = value; }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("Metadata")]
            public MetadataType[] Metadata
            {
                get { return this.metadataField; }
                set { this.metadataField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("ReferenceGroup", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class ReferenceGroupType : BasicIdentificationType
        {

            private AbstractReferenceBaseType[] abstractReferenceBaseField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("AbstractReferenceBase")]
            public AbstractReferenceBaseType[] AbstractReferenceBase
            {
                get { return this.abstractReferenceBaseField; }
                set { this.abstractReferenceBaseField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("Manifest", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class ManifestType : BasicIdentificationType
        {

            private ReferenceGroupType[] referenceGroupField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("ReferenceGroup")]
            public ReferenceGroupType[] ReferenceGroup
            {
                get { return this.referenceGroupField; }
                set { this.referenceGroupField = value; }
            }
        }

        /// <remarks/>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
        [System.SerializableAttribute()]
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.opengis.net/ows/1.1")]
        [System.Xml.Serialization.XmlRootAttribute("ServiceReference", Namespace = "http://www.opengis.net/ows/1.1",
            IsNullable = false)]
        public partial class ServiceReferenceType : ReferenceType
        {

            private object itemField;

            /// <remarks/>
            [System.Xml.Serialization.XmlElementAttribute("RequestMessage", typeof (object))]
            [System.Xml.Serialization.XmlElementAttribute("RequestMessageReference", typeof (string),
                DataType = "anyURI")]
            public object Item
            {
                get { return this.itemField; }
                set { this.itemField = value; }
            }
        }
    }
}